# Generated by Django 4.2.7 on 2023-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('agent', models.CharField(max_length=50)),
                ('form', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=500)),
                ('need', models.CharField(max_length=500)),
                ('non', models.CharField(max_length=500)),
                ('subAction', models.CharField(max_length=500)),
            ],
        ),
    ]
